### ISSUE TITLE
📅 Weekly meeting (2019-08-12)

### ISSUE THREAD

**Issue by pbakaus** [ampproject/wg-outreach#17]
This is wg-outreach's regular weekly meeting with varying agenda, usually presented by wg-outreach members. Mostly meant for wg-outreach regulars, but open for anyone who'd like to contribute to AMP outreach.

**Meeting date/time (UTC)**
17:00 (10am PT)

**Instructions for joining the meeting**
Please join us on Google Meet with [this link](https://meet.google.com/hvn-ihfs-tnz).

**Agenda**
*Note: Add a comment on this issue to propose items for the agenda.*

-  [Paul] a11y for outreach (demos/examples/etc)

**Comment by jaygray0919** [comment]
getting a 404 on the above link

**Comment by mrjoro** [comment]
I believe it should be https://meet.google.com/hvn-ihfs-tnz

**Comment by pbakaus** [comment]
[Ben] Volunteer to help refresh roadshow talks!
[Sebastian] amp.dev translations: when do we have enough content translated to add a new language? [Maybe better suited for the wg-outreach meeting.]
