### ISSUE TITLE
AMP AC outreach tools

### ISSUE THREAD

**Issue by cvazac** [ampproject/wg-outreach#2]
Hello! 

The AMP AC would like to establish the following and is looking to wg-outreach for a sanity check:
1) a twitter handle
We intend to use the account to broadcast our meeting notes, blog posts, etc.  Sadly, `@AMPAC` and `@amp_ac` are taken. `@AMPAdvisoryCommittee` is available, for now. :)

2) a blog platform
Would www.ampproject.org/latest/blog/ be an appropriate place for us to detail things we've done on a ~monthly cadence? If so, is there someone that can help set us up with access to the CMS?

WDYT?

cc @tobie

**Comment by pbakaus** [comment]
Hi @cvazac!

1. not a bad idea, but very difficult for us at Google to get approved, if we are the ones setting it up. Alternatively, we can definitely use `@amphtml` to post occasional updates and blog posts. /cc @mattludwig

2. Yep, I'd definitely encourage you to post on the AMP blog, and to not have a separate one. We are currently migrating the blog for the upcoming launch of our newly refreshed site, but can set up access for everyone who needs it. Who should get accounts?

**Comment by senthilp** [comment]
+1 to use the AMP blog itself for AC outcomes.

**Comment by mattludwig** [comment]
Thanks for tagging me in. I'd agree that in both cases we ought to use the existing channels if at all possible. The updates from the AC will likely be valuable for the audiences of both our existing channels and developing a new audience on a new Twitter handle or blog can be difficult.

**Comment by lisaychuang** [comment]
I just learned about the Working Group from [yesterday's post up on AMP blog](https://amphtml.wordpress.com/2019/03/06/encouraging-more-voices-in-amp/), so I definitely think it will be valuable to keep the existing channels. 

Perhaps the new blog can have a field for author, which can be link to a _AMP AC committee_ shared profile?  Or link to individual authors for the post, and the author's bio can note that she/he is a member of the AC or TSC.

It's been great to see past [TSC meeting minutes](https://github.com/ampproject/meta-tsc/issues?utf8=%E2%9C%93&q=+label%3A%22TSC+Meeting%22+) documented on Github too!

@pbakaus is there a timeline published for the relaunch of AMP website? Perhaps it will be helpful to include guidelines as to how people can request for access to the CMS, assuming authorization & roles can be set up for contributors / editors etc.

**Comment by pbakaus** [comment]
@lisaychuang no timeline published. We're pretty delayed already, but hoping to wrap up most loose ends this week. These kinds of guidelines are definitely needed, looping in @CrystalOnScript, @matthiasrohmer and @sebastianbenz, as they've mostly handled those kinds of contribution guides in the past and can help.

**Comment by sebastianbenz** [comment]
@lisaychuang contribution guides are definitely on the roadmap. They won't be ready for the launch of amp.de though.

**Comment by pbakaus** [comment]
contribution guides are now in, see: https://github.com/ampproject/amp.dev/commit/a6e734a310bfe25d77c4e2be9f028613896914da.

Closing this issue for now. @lisaychuang I know this might not answer your questions, feel free to open individual specific issues and we'll jump on them!
