### ISSUE TITLE
Intent to change facilitator from @pbakaus to @sbenz

### ISSUE THREAD

**Issue by pbakaus** [ampproject/wg-outreach#58]
I'd like to make @sebastianbenz the new facilitator for the outreach working group going forward, as he'll be leading day-to-day projects for Google's AMP DevRel team as well.

If there are no objections, I'll implement this change in the next 48 hours.

Thanks!

**Comment by mrjoro** [comment]
Let's do it!

**Comment by pbakaus** [comment]
Done via 9c0c30d!

**Comment by matthiasrohmer** [comment]
There are still some places were this needs to be updated: GitHub repo description and METADATA.yaml.

**Comment by pbakaus** [comment]
Good catch @matthiasrohmer. Fixed both!
