### ISSUE TITLE
 Add OpenJS Foundation logo and footer to project website

### ISSUE THREAD

**Issue by tobie** [ampproject/wg-outreach#60]
~~Blocked pending language from OpenJS Foundation board, see https://github.com/openjs-foundation/cross-project-council/issues/280.~~

Related to https://github.com/ampproject/wg-foundation-onboarding/issues/12 ~~pending clarifications from OpenJS Foundation CPC.~~

- [x] Add logo to website
- [x] Add footer to website

**Comment by mrjoro** [comment]
/cc @ampproject/wg-outreach 

tentatively assigning to @sebastianbenz

**Comment by brianwarner** [comment]
Hi all,

Providing an update - we are just about to take a vote on the final legal documents.  Once that's done, I will be able to provide you with a standard text to use as the website footer.

**Comment by tobie** [comment]
You'll find the logos and style guide for adding the OpenJSF logo to amp.dev here: https://github.com/openjs-foundation/artwork

**Comment by tobie** [comment]
Additionally, here's text for the footer in both markdown and HTML:

## Markdown

``` markdown
Copyright [OpenJS Foundation](https://openjsf.org) and AMP Project contributors. All rights reserved. The [OpenJS Foundation](https://openjsf.org) has registered trademarks and uses trademarks. For a list of trademarks of the [OpenJS Foundation](https://openjsf.org), please see our [Trademark Policy](https://trademark-policy.openjsf.org/) and [Trademark List](https://trademark-list.openjsf.org/). Trademarks and logos not indicated on the [list of OpenJS Foundation trademarks](https://trademark-list.openjsf.org) are trademarks™ or registered® trademarks of their respective holders. Use of them does not imply any affiliation with or endorsement by them.

[The OpenJS Foundation](https://openjsf.org/) | [Terms of Use](https://terms-of-use.openjsf.org/) | [Privacy Policy](https://privacy-policy.openjsf.org/) | [OpenJS Foundation Bylaws](https://bylaws.openjsf.org/) | [Trademark Policy](https://trademark-policy.openjsf.org/) | [Trademark List](https://trademark-list.openjsf.org/) | [Cookie Policy](https://www.linuxfoundation.org/cookies/)
```

## HTML

```html
<p>Copyright <a href="https://openjsf.org">OpenJS Foundation</a> and AMP Project contributors. All rights reserved. The <a href="https://openjsf.org">OpenJS Foundation</a> has registered trademarks and uses trademarks. For a list of trademarks of the <a href="https://openjsf.org">OpenJS Foundation</a>, please see our <a href="https://trademark-policy.openjsf.org">Trademark Policy</a> and <a href="https://trademark-list.openjsf.org">Trademark List</a>. Trademarks and logos not indicated on the <a href="https://trademark-list.openjsf.org">list of OpenJS Foundation trademarks</a> are trademarks&trade; or registered&reg; trademarks of their respective holders. Use of them does not imply any affiliation with or endorsement by them.</p>
<p><a href="https://openjsf.org">The OpenJS Foundation</a> | <a href="https://terms-of-use.openjsf.org">Terms of Use</a> | <a href="https://privacy-policy.openjsf.org">Privacy Policy</a> | <a href="https://bylaws.openjsf.org">OpenJS Foundation Bylaws</a> | <a href="https://trademark-policy.openjsf.org">Trademark Policy</a> | <a href="https://trademark-list.openjsf.org">Trademark List</a> | <a href="https://www.linuxfoundation.org/cookies">Cookie Policy</a></p>
```

**Comment by matthiasrohmer** [comment]
Thanks, @tobie! Created https://github.com/ampproject/amp.dev/issues/3892 - I think I've read somewhere that we need additional legal information on amp.dev about cdn.ampproject.org as long as its owned by Google..? But might also that I am confusing things here - just wanted to bring it up, maybe it rings anyone's bells 😉

**Comment by tobie** [comment]
@matthiasrohmer tracked here: https://github.com/openjs-foundation/project-onboarding/issues/39. 

Waiting to hear back from @brianwarner on this topic. Not a blocker for onboarding, though.

**Comment by brianwarner** [comment]
Sorry for letting this go so long, I thought I'd answered that one, but must not have.  I'll comment on the other thread, too.

The privacy policy (linked from the footer, and available at https://privacy-policy.openjsf.org) has this section which would cover a CDN:

> Links to Third Party Sites and Services
> The Sites may contain links to third party sites or online services. Please refer to the privacy policies of the relevant third party websites or services to find out more about how they process and handle personal information.

**Comment by matthiasrohmer** [comment]
Thanks, @brianwarner! 🙂 Then I guess we just need to state somewhere that the services available under `cdn.ampproject.org` are provided by Google and point to their Privacy Policy from there as we do currently from the footer.

@sebastianbenz, any idea where to put this and have it discoverable?

**Comment by sebastianbenz** [comment]
I'd put this under the OpenJS trademark statement.

**Comment by tobie** [comment]
https://github.com/ampproject/amp.dev/pull/3942 needs approval by foundation onboarding WG.

**Comment by tobie** [comment]
Approved with a [slight rewording request](https://github.com/ampproject/amp.dev/pull/3942#discussion_r427619155).
