### ISSUE TITLE
Choose a date and location for the AMP Contributor Summit 2020

### ISSUE THREAD

**Issue by mrjoro** [ampproject/wg-outreach#82]
**Update: we are now planning on merging the AMP Contributor Summit into the OpenJS Collab Summit, which will be held virtually the week of June 22, 2020.  See the issue comments for more info.**

~Based on the results of an [informal survey](https://amphtml.slack.com/archives/C9HRJ1GPN/p1578427462003700), we're aiming to have the AMP Contributor Summit:~

- ~either the week of September 14, 2020 or October 5, 2020~
- ~in the central US (likely Austin, Texas or Denver/Boulder, Colorado) or Mexico City~

~I'd like to get feedback from the community to help determine the final date and location.~

- ~is there any reason we should be aware of that the week of September 14 or October 5 is better, e.g. holidays, other big conferences with a similar audience, etc.?~
- ~is there any reason we should choose a particular location over the others?~

~I know last year some people had visa issues that kept them from entering the US.  For anyone affected by this, would Mexico be easier to enter, and if so would travel there be feasible?~

~Please respond to this issue with your thoughts, or if you prefer you can contact me (@mrjoro) on Slack.~

**Comment by mrjoro** [comment]
We are strongly leaning towards merging the AMP Contributor Summit into the [OpenJS Collab Summit](https://events.linuxfoundation.org/openjs-world/features/openjs-collaborator-summit/), which will be held virtually the week of June 22.

There are several good reasons for this move, including:

- As an incubating project in the OpenJSF, participating in the OpenJSF Collab Summit allows us to more fully be part of the wider community.
- With the Covid-19 situation there was too much uncertainty to plan an in-person summit this year, so we were already considering making the AMP Contributor Summit a virtual summit.  Because the OpenJSF Collab Summit is being held virtually we are able to take advantage of the unique planning / best practices that hosting a virtual summit requires.
- The OpenJSF Collab Summit is already set up to provide time for the three main components of the AMP Contributor Summit (the New Contributor Day, talks and breakout sessions).
- The OpenJSF Collab Summit allows for multiple tracks, so that we will be able to have the same amount of AMP content as in past AMP Contributor Summits.

If there are no objections, we will move forward with this plan.

/cc @ampproject/wg-outreach @ampproject/tsc @jorydotcom

**Comment by morsssss** [comment]
sgtm! I think it would be wonderful to take this opportunity to build closer ties with OpenJS - and to make it simpler for the larger open-source community to check out what's happening in the AMP project.

**Comment by davidstrauss** [comment]
+1 on consolidating with OpenJS Collab Summit.

I find some of my most valuable learning has come from multidisciplinary exposure, especially through events that make it easy to view talks that seem interesting even if they're not directly related to my primary focus. Being part of a larger event encourages that kind of exposure for attendees.

**Comment by rudygalfi** [comment]
This seems obsolete / resolved. I'll close it.
